export interface Project {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  year: string;
  region: string;
  image: string;
  imageAlt: string;
  galleryImages: { src: string; alt: string; left?: boolean }[];
  overview: string;
  details: string;
  metadata?: Array<{ label: string; value: string }>;
  nextSlug?: string;
  nextTitle?: string;
  nextThumb: string;
  nextThumbAlt: string;
}

export const PROJECTS: Project[] = [
  {
    slug: 'hubble-street',
    title: 'Hubble Street',
    subtitle: 'Master Ensuite, Main Bathroom, Large Family Powder Room',
    description: 'A defining collaboration with builder Arklen on a heritage cottage rear extension in East Fremantle.',
    year: '2023',
    region: 'East Fremantle, WA',
    image: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/32250_2-1_Hskawwzb1.jpg?tr=w-1170,h-768,q-80',
    imageAlt: 'A modern kitchen featuring a well-lit splash-back of cream vertical stack tiles.',
    galleryImages: [
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0215_6G85vEGOI.jpg?tr=w-1680,h-1228,q-80', alt: 'Modern kitchen with under cabinet lighting illuminating a vertical stack tiled splash-back.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0259_FjBaNLFXm.jpg?tr=w-1680,h-1228,q-80', alt: 'A white bathroom with wooden cabinet, featuring a white tiled surrounding wall.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0295_rq02VAeDo.jpg?tr=w-840,h-1228,q-80', alt: 'A modern shower with white tiling.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0280_fWMiWRIIF.jpg?tr=w-840,h-1228,q-80', alt: 'Modern white bathroom with wooden cabinets with white tiling on the walls.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0355-1_QJlsZGdiw.jpg?tr=w-1680,h-1228,q-80', alt: 'Sleek bathroom counter with an exposed brick feature wall and tall vertical green tiling to accent it.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0337-1__jNx8eoxz.jpg?tr=w-840,h-1228,q-80', alt: 'Off white and green vertical stacked tiling on a bathroom wall.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_0373_T15UDw_pk.jpg?tr=w-1680,h-1228,q-80', alt: 'Modern bathroom with a white counter and sink with an arched mirror above, surrounded by green and off-white vertical stacked tiling.' },
    ],
    overview: '––– This Hubble Street home in East Fremantle marked a defining moment for Marvell Tile and Stone in Western Australia. Their first collaboration with builder Arklen, this rear extension to a heritage cottage seamlessly blends old and new, showcasing beautiful detailing, refined materiality, and the fine craftsmanship that has since become Marvell\'s signature.',
    details: '––– Discovered by Arklen through social media soon after relocating from London, William Marvell and his team were engaged to complete this Hubble Street home\'s three wet areas — a master ensuite, kids\' bathroom, and family powder room. This project became a foundation for their Western Australian practice and the start of an enduring partnership built on skill and shared standards.\n\nA refined palette of dual-format matte white wall tiles and terrazzo floors anchors each space with texture and balance. In the master ensuite, two colourways of subway tiles were laid in a vertical stack bond, establishing rhythm and order. Every surface reflects craftsmanship — mixed tile formats align perfectly at corners, grout lines run seamlessly through adjoining rooms, and symmetry is carefully maintained throughout. The result is a collection of calm, timeless spaces that reflect both Arklen\'s and Marvell\'s skill, vision and execution, setting the tone for their future work across Perth\'s design landscape.',
    metadata: [
      { label: 'Builder', value: 'Arklen' },
      { label: 'Architect / Designer', value: 'Lahaus' },
      { label: 'Tile / Terrazzo Supplier', value: 'Artedomus' },
      { label: 'Photographer', value: 'Peter Ellery Photography' },
    ],
    nextSlug: 'sewell-street',
    nextTitle: 'Sewell Street',
    nextThumb: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3568-cropped_YHAqn7tTJ.jpg?tr=w-140,h-140,q-80',
    nextThumbAlt: 'A frontal view of the detailed stonework on the stairs.',
  },
  {
    slug: 'sewell-street',
    title: 'Sewell Street',
    subtitle: 'Outdoor Paving & Pool Surrounds',
    description: 'Detailed stonework and paving for a contemporary Perth home.',
    year: '2023',
    region: 'Subiaco, WA',
    image: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3568-cropped_YHAqn7tTJ.jpg?tr=w-1170,h-768,q-80',
    imageAlt: 'A frontal view of the detailed stonework on the stairs.',
    galleryImages: [
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3568-cropped_YHAqn7tTJ.jpg?tr=w-1680,h-1228,q-80', alt: 'A frontal view of the detailed stonework on the stairs.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3571-cropped_YjFBcWVjo.jpg?tr=w-840,h-1228,q-80', alt: 'Birds-eye view of stone tiled stairway leading from the driveway.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3556-cropped_bdzE6D29J.jpg?tr=w-840,h-1228,q-80', alt: 'A striking white house facade with detailed stonework on the stairs.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_8846_qQYBah9oW.jpeg?tr=w-840,h-1228,q-80', alt: 'Birdseye view of private pool with a stone tiled border.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_8864_J5POGg-uW.jpeg?tr=w-1680,h-1228,q-80', alt: 'Small private pool featuring stone tiling and surrounding garden.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_8962-cropped_-RpWZ2TD3.jpg?tr=w-840,h-1228,q-80', alt: 'Pool featuring stone tiling and greenery.' },
      { src: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/DSC_3571-cropped_YjFBcWVjo.jpg?tr=w-1680,h-1228,q-80', alt: 'Detailed stone pathway leading to front entrance.' },
    ],
    overview: '––– The Sewell Street project showcases Marvell\'s expertise in outdoor stone installation. A complete transformation of the home\'s exterior spaces, featuring hand-selected natural stone paving across multiple terraces and pool surrounds.',
    details: '––– Working in close collaboration with the landscape architect, Marvell sourced and installed a cohesive selection of natural stone across the driveway, stairs, pathways, and pool border. The result is a seamless transition from street to pool — a quiet, confident landscape that lets the material speak.\n\nEvery slab was set by hand, with particular attention to joint width consistency and directional coursing. The pool border required specialist waterproofing detailing beneath, while the stair nosings were custom-cut to radius to match the curved retaining wall above.',
    metadata: [
      { label: 'Builder', value: 'Talo Constructions' },
      { label: 'Stone Supplier', value: 'Artedomus' },
      { label: 'Photographer', value: 'Peter Ellery Photography' },
    ],
    nextSlug: 'hubble-street',
    nextTitle: 'Hubble Street',
    nextThumb: 'https://ik.imagekit.io/isclzlt7q/marvell-production/images/32250_2-1_Hskawwzb1.jpg?tr=w-140,h-140,q-80',
    nextThumbAlt: 'A modern kitchen with cream vertical stack tile backsplash.',
  },
  {
    slug: 'wild-horizons',
    title: 'Wild Horizons',
    subtitle: 'Landscape Photography & Quiet Architecture',
    description: 'Alpine peaks, tropical shores, and the homes that live quietly alongside them.',
    year: '2024 — 2026',
    region: 'Dolomites · Pacific · Iceland',
    image: '/images/hero-main.jpg',
    imageAlt: 'A vivid alpine sunset washing color across mountain peaks.',
    galleryImages: [
      { src: '/images/gallery-1.jpg', alt: 'A modern luxury home framed by lush tropical plants at twilight.', left: true },
      { src: '/images/gallery-2.jpg', alt: 'A lone palm tree leaning over a tropical paradise beach.' },
      { src: '/images/gallery-3.jpg', alt: 'A misty green mountain forest disappearing into low cloud.', left: true },
      { src: '/images/gallery-4.jpg', alt: 'The majestic Skogafoss waterfall cascading down a cliff in Iceland.' },
      { src: '/images/gallery-5.jpg', alt: 'Panoramic sunset view of the Oregon coastline at golden hour.' },
    ],
    overview: `–––Wild Horizons is a study of the places that quiet the mind — sunset-streaked alpine peaks, palms leaning over warm coastal water, forests softened by morning fog, and the architecture that lives alongside them.`,
    details: `Shot across three continents over eighteen months, this series follows a simple brief: photograph places that feel both improbably large and unmistakably personal. Every image is unedited beyond color and contrast — no compositing, no relocations, no false skies.`,
    nextSlug: 'quiet-forests',
    nextTitle: 'Quiet Forests',
    nextThumb: '/images/next-project-eco-thumb.jpg',
    nextThumbAlt: 'Sun rays piercing through a misty forest at dawn',
  },
  {
    slug: 'quiet-forests',
    title: 'Quiet Forests',
    subtitle: 'Woodland Light & Stillness',
    description: 'Ancient canopies, morning mist, and the slow patience of old growth.',
    year: '2024',
    region: 'Pacific Northwest · Scandinavia',
    image: '/images/next-project-eco-thumb.jpg',
    imageAlt: 'Sun rays piercing through a misty forest at dawn.',
    galleryImages: [
      { src: '/images/gallery-3.jpg', alt: 'A misty green mountain forest disappearing into low cloud.', left: true },
      { src: '/images/gallery-5.jpg', alt: 'Panoramic view of a forest coastline at golden hour.' },
      { src: '/images/gallery-1.jpg', alt: 'A cabin nestled in a forest clearing at dusk.', left: true },
      { src: '/images/gallery-4.jpg', alt: 'Light filtering through tall ancient trees.' },
      { src: '/images/gallery-2.jpg', alt: 'A quiet path winding through a dense forest.' },
    ],
    overview: `–––Quiet Forests is an exploration of stillness — the kind found only in places where trees have been growing longer than anyone alive can remember. Dawn light through old-growth canopy. The sound of nothing in particular.`,
    details: `Photographed across the Pacific Northwest and Scandinavia, this series seeks the places where the forest feels truly sovereign — where architecture, when it appears, is always deferential. Small, dark, careful.`,
    nextSlug: 'coastal-light',
    nextTitle: 'Coastal Light',
    nextThumb: '/images/gallery-5.jpg',
    nextThumbAlt: 'Panoramic sunset view of the Oregon coastline',
  },
  {
    slug: 'coastal-light',
    title: 'Coastal Light',
    subtitle: 'Shoreline Studies',
    description: 'Where land concedes to ocean — the architecture of edges.',
    year: '2025',
    region: 'Oregon · Amalfi · Algarve',
    image: '/images/gallery-5.jpg',
    imageAlt: 'Panoramic sunset view of the Oregon coastline at golden hour.',
    galleryImages: [
      { src: '/images/gallery-1.jpg', alt: 'A coastal home at twilight.', left: true },
      { src: '/images/gallery-2.jpg', alt: 'A palm framing the horizon.' },
      { src: '/images/gallery-5.jpg', alt: 'The Oregon coast going pink at dusk.', left: true },
      { src: '/images/gallery-4.jpg', alt: 'Coastal cliffs and waterfalls.' },
      { src: '/images/gallery-3.jpg', alt: 'Sea mist rising over coastal hills.' },
    ],
    overview: `–––Coastal Light examines the boundary where land ends — and the human instinct to build right at the edge of it. These photographs document both the drama of shorelines and the quiet homes that choose to live alongside that drama.`,
    details: `From the rugged drama of the Oregon coast to the warm terracotta of the Algarve, each location was chosen for its quality of light in the late afternoon — the hour when coastal landscapes stop posing and start simply existing.`,
    nextSlug: 'alpine-studies',
    nextTitle: 'Alpine Studies',
    nextThumb: '/images/hero-main.jpg',
    nextThumbAlt: 'Alpine peaks at sunset',
  },
  {
    slug: 'alpine-studies',
    title: 'Alpine Studies',
    subtitle: 'Elevation & Clarity',
    description: 'Above the treeline, where light is sharper and silence is absolute.',
    year: '2025',
    region: 'Dolomites · Swiss Alps · Patagonia',
    image: '/images/hero-main.jpg',
    imageAlt: 'A vivid alpine sunset washing color across mountain peaks.',
    galleryImages: [
      { src: '/images/gallery-4.jpg', alt: 'A dramatic waterfall in a mountain valley.', left: true },
      { src: '/images/gallery-1.jpg', alt: 'A mountain retreat at last light.' },
      { src: '/images/hero-main.jpg', alt: 'Alpine peaks at sunset.', left: true },
      { src: '/images/gallery-3.jpg', alt: 'Clouds rolling over a mountain ridge.' },
      { src: '/images/gallery-5.jpg', alt: 'The long shadow of a peak across a valley.' },
    ],
    overview: `–––Alpine Studies is an investigation of altitude — what happens to color, sound, and proportion when you climb above the treeline. The light is harder and more direct. The shadows are sharper. Everything feels both larger and simpler.`,
    details: `Photographed across the Dolomites, the Swiss Alps, and Patagonia over two summers. Each location was visited at least twice — once in morning light and once at golden hour — to understand how the same peak can feel like two completely different places.`,
    nextSlug: 'sea-and-stone',
    nextTitle: 'Sea & Stone',
    nextThumb: '/images/gallery-2.jpg',
    nextThumbAlt: 'Tropical coastline with stone formations',
  },
  {
    slug: 'sea-and-stone',
    title: 'Sea & Stone',
    subtitle: 'Geological Portraits',
    description: 'Basalt, limestone, and the patient erosion of ten thousand years.',
    year: '2025',
    region: 'Iceland · Azores · Big Sur',
    image: '/images/gallery-2.jpg',
    imageAlt: 'A lone palm tree leaning over a tropical paradise beach.',
    galleryImages: [
      { src: '/images/gallery-4.jpg', alt: 'Basalt cliffs at the edge of the Atlantic.', left: true },
      { src: '/images/gallery-2.jpg', alt: 'Volcanic stone and ocean spray.' },
      { src: '/images/gallery-5.jpg', alt: 'Limestone coast at low tide.', left: true },
      { src: '/images/gallery-3.jpg', alt: 'Sea-worn rocks at Big Sur.' },
      { src: '/images/gallery-1.jpg', alt: 'A stone house on the Azores coast.' },
    ],
    overview: `–––Sea & Stone is a portrait series of geology — specifically the places where ancient rock meets contemporary ocean. These images ask: what does a landscape look like after ten thousand years of conversation with the sea?`,
    details: `Iceland, the Azores, and Big Sur each offer a different answer. Iceland is volcanic and dramatic, the stone still feeling newly formed. The Azores are weather-worn and intimate. Big Sur is stoic — cliffs that have watched countless seasons and offered no opinion.`,
    nextSlug: 'northern-falls',
    nextTitle: 'Northern Falls',
    nextThumb: '/images/gallery-4.jpg',
    nextThumbAlt: 'Iceland waterfall at dusk',
  },
  {
    slug: 'northern-falls',
    title: 'Northern Falls',
    subtitle: 'Water in Motion',
    description: 'The force and silence of water that has been falling for centuries.',
    year: '2026',
    region: 'Iceland · Norway · British Columbia',
    image: '/images/gallery-4.jpg',
    imageAlt: 'The majestic Skogafoss waterfall cascading down a cliff in Iceland.',
    galleryImages: [
      { src: '/images/gallery-4.jpg', alt: 'Skogafoss waterfall in full flow.', left: true },
      { src: '/images/gallery-3.jpg', alt: 'Mist rising from a Norwegian waterfall.' },
      { src: '/images/gallery-5.jpg', alt: 'A coastal waterfall meeting the ocean.', left: true },
      { src: '/images/gallery-1.jpg', alt: 'A homestead near a British Columbia falls.' },
      { src: '/images/hero-main.jpg', alt: 'The valley carved by centuries of falling water.' },
    ],
    overview: `–––Northern Falls is a meditation on water in its most theatrical form. These are places where rivers simply run out of ground — and the result, after centuries, is both violent and beautiful in ways that no single photograph can fully hold.`,
    details: `The series spans Iceland's Skogafoss and Gullfoss, a half-dozen unnamed falls in Norway's fjord country, and the rain-fed cataracts of coastal British Columbia. Shot in both long exposure and at shutter speeds fast enough to freeze individual droplets.`,
    nextSlug: 'wild-horizons',
    nextTitle: 'Wild Horizons',
    nextThumb: '/images/hero-main.jpg',
    nextThumbAlt: 'Alpine sunset over mountain peaks',
  },
];

export function getProject(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}
